### PR TITLE
Added a solution to Codeforces Beta Round #40 Div 2 A

### PR DESCRIPTION
**Pull request by ayushh7**
Added a solution to the translation program in codeforces.
Please merge my PR.

### CODE REVIEW

**Comment by abhijeetkumarsinghofficial** [comment]
> Added a solution to the translation program in codeforces. Please merge my PR.

Great work

**Comment by ayushh7** [comment]
> > Added a solution to the translation program in codeforces. Please merge my PR.
> 
> Great work

Thanks 😊

**Comment by ayushh7** [comment]
image
You have not added a label to the PRs in this repo?

**Comment by ayushh7** [comment]
ohkk. thanks..

**Pull request merged**
